# TOML

title = "default settings for LogSet tools"

verbosity = "warning"

[persistence]
    persistence = "SQLite3"
    name = "logs.db"

[namespaces]
    base = "https://portal.nersc.gov/project/m888/resilience/datasets"
