# TOML

title = "default settings for LogSet tools"

verbosity = "warning"

[persistence]
    persistence = "SQLite3"
    name = "logs.db"

[namespaces]
    # namespaces used in all graphs
    rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    rdfs = "http://www.w3.org/2000/01/rdf-schema#"
    owl = "http://www.w3.org/2002/07/owl#"
    xsd = "http://www.w3.org/2001/XMLSchema#"
    foaf = "http://xmlns.com/foaf/0.1/"
    skos = "http://www.w3.org/2004/02/skos/core#"
    doap = "http://usefulinc.com/ns/doap#"
    dc = "http://purl.org/dc/elements/1.1/"
    dct = "http://purl.org/dc/terms/"
    xml = "http://www.w3.org/XML/1998/namespace"
    dcat = "http://www.w3.org/ns/dcat#"
    vcard = "https://www.w3.org/2006/vcard/ns"
    adms = "http://www.w3.org/ns/adms#"

[bindings]
    # additional preferred bindings
    logset = "https://portal.nersc.gov/project/m888/resilience/datasets/logset#"
    ddict = "https://portal.nersc.gov/project/m888/resilience/datasets/ddict#"
